# Generated by Django 5.2.4 on 2025-08-03 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_date_created_ticket_date_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.CharField(choices=[('avicenna', 'کارخانه دارو سازی آوه سینا'), ('arasto', 'کارخانه دارو سازی ارسطو')], default='avicenna', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='unit',
            field=models.CharField(choices=[('qa', 'واحد تضمین کیفیت'), ('storage', 'واحد انبار'), ('production', 'واحد تولید'), ('manager', 'مدیریت کارخانه'), ('office', 'واحد اداری'), ('technical', 'واحد فنی')], default='manager', max_length=200),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال رسیدگی'), ('completed', 'انجام شد'), ('aborted', 'لغو شده')], default='open', max_length=200),
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reply', to='ticketing.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
