# Generated by Django 5.2.4 on 2025-08-07 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_alter_ticket_company_alter_ticket_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticketing.ticket'),
        ),
    ]
