# Generated by Django 5.2.4 on 2025-07-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avicennacomment',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='avicennacomment',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
