# Generated by Django 5.2.4 on 2025-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personnel_code',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
