# Generated by Django 5.2.4 on 2025-10-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupsdata',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
