# Generated by Django 5.2.4 on 2025-10-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_popupsdata_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopUpsData',
            new_name='Modal',
        ),
    ]
